# FORM TYPE
TYPE_NOT_QUIZ = 0
TYPE_QUIZ     = 1

# FORM STATUS
STATUS_UNPUBLISHED = 0
STATUS_PUBLISHED   = 1
STATUS_FINISHED    = 2

# QUESTION TYPE
QUESTION_MULTIPLE_CHOICE = 1
QUESTION_CHECKBOX        = 2
QUESTION_SHORT_ANSWER    = 3
QUESTION_PARAGRAPH       = 4

# OPTION TYPE
OPTION_OTHER     = 1
OPTION_NOT_OTHER = 0

# SCORE
DEFAULT_SCORE = 0